### ISSUE TITLE
[Feature Request] Need a way to customize paths

### ISSUE THREAD

**Issue by brianwestphal** [natrim/esbuild-plugin-inline-image#3]
- The outdir path from esbuild isn't necessarily the best place for images (ex. I put mine in `'./build/static/js'`, so maybe `'./build/static/images'` would be better)
- Need a way to prefix non-inlined images relative to the host (ex. this currently generates paths like `'./pop-P6TXCLHE.svg'`, but `'/static/images/pop-P6TXCLHE.svg'` would be better)

Thanks!

**Comment by natrim** [comment]
this plugin does not change any paths, it only inlines image if smaller than defined size
(inline means it puts it together with the js code as dataurl (ie. same as css inlined images))
it does nothing to the images otherwise

btw. [you can change the images outputpath in esbuild config by setting assetnames](https://esbuild.github.io/api/#asset-names)
